exclude = [
    "__pycache__",
    ".git",
    ".pytest_cache",
    ".idea",
    "i18n",
    "icons",
    "packages",
    "dbmodel",
    "test",
    "i18n_manager.py",
    "schema_i18n_update.py",
    "i18n_generator.py",
    "markdown_generator.py",
]
line-length = 120

[lint]
select = ["E2", "E3", "E4", "E7", "E9", "N8", "D1", "D2", "D3", "D4", "C90", "F4", "F541", "F8", "F9"]

[lint.mccabe]
max-complexity = 40
